server:
  port: 8080
ice:
  jwt:
    location: classpath:ice.jks
    alias: ice
    password: ice5626
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi