knife4j:
  enable: true
  openapi:
    title: ice
    description: "冰块商城接口文档"
    email: jlau.ice@gmail.com
    concat: ice
    url: https://dryice.icu
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - ${ice.swagger.package}